"""
dashboard.py
============
Urban Environmental Intelligence – Interactive Dashboard
Data source: data/processed/*.parquet (generated by task1–task4 scripts)
Run: streamlit run dashboard.py
"""

import warnings
import math
from pathlib import Path

import numpy as np
import polars as pl
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import streamlit as st

warnings.filterwarnings("ignore")

PROCESSED_DIR  = Path("data/processed")
PM25_THRESHOLD = 35.0

C_RED    = "#e63946"
C_BLUE   = "#457b9d"
C_GREEN  = "#2d6a4f"
C_ORANGE = "#f4a261"
GRID_CLR = "rgba(255,255,255,0.07)"
FONT_CLR = "#c9d1d9"
PLOT_BG  = "rgba(0,0,0,0)"

ZONE_COLOURS = {"Industrial": C_RED, "Residential": C_BLUE}


# ─────────────────────────────────────────────────────────────────────────────
# CSS
# ─────────────────────────────────────────────────────────────────────────────

CSS = """
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&family=DM+Mono:wght@400;500&display=swap');

html, body,
[data-testid="stAppViewContainer"],
[data-testid="stApp"] {
    background: #0d0f1a !important;
    color: #c9d1d9 !important;
    font-family: 'DM Sans', sans-serif !important;
}

/* top accent bar */
[data-testid="stAppViewContainer"]::before {
    content: '';
    position: fixed;
    top: 0; left: 0; right: 0;
    height: 3px;
    background: linear-gradient(90deg, #e63946 0%, #457b9d 40%, #2d6a4f 70%, #f4a261 100%);
    z-index: 9999;
}

[data-testid="stHeader"] { background: transparent !important; }

/* sidebar */
[data-testid="stSidebar"] {
    background: #0a0c14 !important;
    border-right: 1px solid rgba(255,255,255,0.05);
}
[data-testid="stSidebar"] * { font-family: 'DM Sans', sans-serif !important; }

/* metric cards */
[data-testid="stMetric"] {
    background: rgba(255,255,255,0.03);
    border: 1px solid rgba(255,255,255,0.07);
    border-radius: 10px;
    padding: 18px 20px !important;
}
[data-testid="stMetric"] label {
    color: #6e7681 !important;
    font-size: 0.72rem !important;
    font-weight: 500 !important;
    text-transform: uppercase;
    letter-spacing: 0.8px;
    white-space: normal !important;
    overflow: visible !important;
    text-overflow: unset !important;
}
[data-testid="stMetricValue"] {
    color: #e6edf3 !important;
    font-size: 1.6rem !important;
    font-weight: 600 !important;
    white-space: normal !important;
    overflow: visible !important;
    text-overflow: unset !important;
    line-height: 1.2 !important;
}
[data-testid="stMetricDelta"] { display: none; }

/* plotly chart wrapper */
.stPlotlyChart {
    background: rgba(255,255,255,0.02);
    border: 1px solid rgba(255,255,255,0.05);
    border-radius: 12px;
    padding: 4px;
}

/* expander */
details {
    background: rgba(255,255,255,0.02) !important;
    border: 1px solid rgba(255,255,255,0.06) !important;
    border-radius: 10px !important;
}
summary { color: #8b949e !important; font-size: 0.85rem !important; }

/* dataframe */
[data-testid="stDataFrame"] { border-radius: 10px; overflow: hidden; }

/* headings */
h1 { font-size: 1.5rem !important; font-weight: 600 !important; color: #e6edf3 !important; }
h2 { font-size: 1.1rem !important; font-weight: 600 !important; color: #c9d1d9 !important; margin-top: 1.4rem !important; }
h3 { font-size: 0.95rem !important; font-weight: 500 !important; color: #8b949e !important; }

/* divider */
hr { border-color: rgba(255,255,255,0.05) !important; margin: 1rem 0 !important; }

/* radio */
[data-testid="stRadio"] label { color: #c9d1d9 !important; font-size: 0.88rem !important; }

/* code */
code {
    background: rgba(255,255,255,0.06) !important;
    color: #79c0ff !important;
    font-family: 'DM Mono', monospace !important;
    border-radius: 4px;
    padding: 1px 5px;
}
pre code { padding: 10px !important; }

/* hide streamlit chrome */
#MainMenu { visibility: hidden; }
footer    { visibility: hidden; }
[data-testid="stToolbar"] { display: none; }
</style>
"""


# ─────────────────────────────────────────────────────────────────────────────
# Plotly layout helper
# ─────────────────────────────────────────────────────────────────────────────

def _layout(**kw):
    base = dict(
        template="plotly_dark",
        plot_bgcolor=PLOT_BG,
        paper_bgcolor=PLOT_BG,
        font=dict(color=FONT_CLR, family="DM Sans, sans-serif", size=12),
        xaxis=dict(gridcolor=GRID_CLR, zeroline=False, linecolor="rgba(255,255,255,0.08)"),
        yaxis=dict(gridcolor=GRID_CLR, zeroline=False, linecolor="rgba(255,255,255,0.08)"),
        margin=dict(l=60, r=30, t=55, b=50),
        hoverlabel=dict(
            bgcolor="#161b27", font_size=12,
            font_family="DM Sans, sans-serif",
            bordercolor="rgba(255,255,255,0.12)",
        ),
        legend=dict(bgcolor="rgba(0,0,0,0)", font_size=11),
    )
    base.update(kw)
    return base


# ─────────────────────────────────────────────────────────────────────────────
# Data loaders
# ─────────────────────────────────────────────────────────────────────────────

@st.cache_data
def load_pca_scores():
    p = PROCESSED_DIR / "task1_pca_scores.parquet"
    return pl.read_parquet(p) if p.exists() else pl.DataFrame()

@st.cache_data
def load_pca_loadings():
    p = PROCESSED_DIR / "task1_pca_loadings.parquet"
    return pl.read_parquet(p) if p.exists() else pl.DataFrame()

@st.cache_data
def load_hourly():
    p = PROCESSED_DIR / "task2_hourly.parquet"
    return pl.read_parquet(p) if p.exists() else pl.DataFrame()

@st.cache_data
def load_seasonal():
    p = PROCESSED_DIR / "task2_seasonal.parquet"
    return pl.read_parquet(p) if p.exists() else pl.DataFrame()

@st.cache_data
def load_stats():
    p = PROCESSED_DIR / "task3_stats.parquet"
    return pl.read_parquet(p) if p.exists() else pl.DataFrame()

@st.cache_data
def load_kde():
    p = PROCESSED_DIR / "task3_kde.parquet"
    return pl.read_parquet(p) if p.exists() else pl.DataFrame()

@st.cache_data
def load_ccdf():
    p = PROCESSED_DIR / "task3_ccdf.parquet"
    return pl.read_parquet(p) if p.exists() else pl.DataFrame()

@st.cache_data
def load_station_summary():
    p = PROCESSED_DIR / "task4_station_summary.parquet"
    return pl.read_parquet(p) if p.exists() else pl.DataFrame()


def _missing(name):
    st.error(f"Processed data for {name} not found. Run `python main.py` first.")


# ─────────────────────────────────────────────────────────────────────────────
# Overview
# ─────────────────────────────────────────────────────────────────────────────

def page_overview():
    st.header("Dataset Overview")

    summary = load_station_summary()
    stats   = load_stats()

    if summary.is_empty():
        _missing("Overview")
        return

    # ── metrics (values pulled directly from processed data) ──
    n_stations  = len(summary)
    n_countries = summary["country"].n_unique() if "country" in summary.columns else 0
    n_regions   = summary["region"].n_unique()
    avg_pm25    = summary["mean_pm25"].mean()
    p99_val     = float(stats["p99"][0]) if not stats.is_empty() else None

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Stations", f"{n_stations}")
    c2.metric("Countries", f"{n_countries}")
    c3.metric("Regions", f"{n_regions}")
    c4.metric("Avg Mean PM2.5", f"{avg_pm25:.1f} µg/m³")
    c5.metric("Station 99th Percentile", f"{p99_val:.1f} µg/m³" if p99_val else "—")

    st.divider()

    col_a, col_b = st.columns(2)

    with col_a:
        st.subheader("Mean PM2.5 by Region")
        region_means = (
            summary.group_by("region")
                   .agg(pl.col("mean_pm25").mean().alias("avg"))
                   .sort("avg", descending=True)
        )
        regions = region_means["region"].to_list()
        vals    = region_means["avg"].to_list()
        colours = [C_RED if v > PM25_THRESHOLD else C_BLUE for v in vals]

        fig = go.Figure(go.Bar(
            y=regions, x=vals, orientation="h",
            marker_color=colours,
            text=[f"{v:.1f} µg/m³" for v in vals],
            textposition="outside",
            textfont=dict(size=10, color=FONT_CLR),
            hovertemplate="<b>%{y}</b><br>Mean PM2.5: %{x:.2f} µg/m³<extra></extra>",
        ))
        fig.add_vline(
            x=PM25_THRESHOLD, line_dash="dash", line_color=C_RED, line_width=1.2,
            annotation_text=f"WHO threshold  {PM25_THRESHOLD} µg/m³",
            annotation_position="top",
            annotation_font=dict(color=C_RED, size=10),
        )
        fig.update_layout(**_layout(
            xaxis_title="Annual mean PM2.5 (µg/m³)",
            height=340,
        ))
        st.plotly_chart(fig, use_container_width=True)

    with col_b:
        st.subheader("Zone Type Comparison")
        zone_df = (
            summary.group_by("zone_type")
                   .agg([
                       pl.col("mean_pm25").mean().alias("avg"),
                       pl.len().alias("n"),
                   ])
                   .sort("zone_type")
        )
        zones  = zone_df["zone_type"].to_list()
        zvals  = zone_df["avg"].to_list()
        zcols  = [ZONE_COLOURS.get(z, "#888") for z in zones]
        counts = zone_df["n"].to_list()

        fig2 = go.Figure(go.Bar(
            x=zones, y=zvals,
            marker_color=zcols, width=0.4,
            text=[f"{v:.1f} µg/m³<br>n = {c}" for v, c in zip(zvals, counts)],
            textposition="outside",
            textfont=dict(size=10, color=FONT_CLR),
            hovertemplate="<b>%{x}</b><br>Mean PM2.5: %{y:.2f} µg/m³<extra></extra>",
        ))
        fig2.add_hline(
            y=PM25_THRESHOLD, line_dash="dash", line_color=C_RED, line_width=1.2,
            annotation_text=f"WHO threshold  {PM25_THRESHOLD} µg/m³",
            annotation_position="top left",
            annotation_font=dict(color=C_RED, size=10),
        )
        fig2.update_layout(**_layout(
            yaxis_title="Annual mean PM2.5 (µg/m³)",
            height=340,
        ))
        st.plotly_chart(fig2, use_container_width=True)

    st.subheader("Station Summary")
    display_cols = [c for c in
                    ["station_id", "zone_type", "region", "country",
                     "mean_pm25", "p95_pm25", "n_readings"]
                    if c in summary.columns]
    st.dataframe(
        summary.select(display_cols)
               .sort("mean_pm25", descending=True)
               .rename({
                   "station_id": "Station",
                   "zone_type":  "Zone",
                   "region":     "Region",
                   "country":    "Country",
                   "mean_pm25":  "Mean PM2.5",
                   "p95_pm25":   "P95 PM2.5",
                   "n_readings": "Readings",
               })
               .to_pandas(),
        use_container_width=True,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Task 1 – PCA
# ─────────────────────────────────────────────────────────────────────────────

def page_task1():
    st.header("Task 1 – Dimensionality Reduction")

    scores_df   = load_pca_scores()
    loadings_df = load_pca_loadings()

    if scores_df.is_empty() or loadings_df.is_empty():
        _missing("Task 1")
        return

    pc1_var = float(scores_df["pc1_variance"][0])
    pc2_var = float(scores_df["pc2_variance"][0])
    n_sta   = len(scores_df)
    combined = pc1_var + pc2_var

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Stations Analysed", f"{n_sta}")
    c2.metric("PC1 Variance", f"{pc1_var*100:.1f}%")
    c3.metric("PC2 Variance", f"{pc2_var*100:.1f}%")
    c4.metric("Combined Variance", f"{combined*100:.1f}%")

    st.divider()
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Principal Component Scatter")
        fig = go.Figure()
        for zone, colour in ZONE_COLOURS.items():
            sub = scores_df.filter(pl.col("zone_type") == zone)
            if len(sub):
                fig.add_trace(go.Scatter(
                    x=sub["pc1"].to_numpy(),
                    y=sub["pc2"].to_numpy(),
                    mode="markers",
                    name=zone,
                    marker=dict(color=colour, size=10, opacity=0.85,
                                line=dict(width=0)),
                    hovertemplate=(
                        f"<b>{zone}</b><br>"
                        "PC1: %{x:.3f}<br>"
                        "PC2: %{y:.3f}<extra></extra>"
                    ),
                ))
        fig.add_hline(y=0, line_color="rgba(255,255,255,0.12)", line_width=0.8)
        fig.add_vline(x=0, line_color="rgba(255,255,255,0.12)", line_width=0.8)
        fig.update_layout(**_layout(
            xaxis_title=f"PC1  ({pc1_var*100:.1f}% variance explained)",
            yaxis_title=f"PC2  ({pc2_var*100:.1f}% variance explained)",
            height=460,
        ))
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("Variable Loadings")
        labels   = loadings_df["display_name"].to_list()
        pc1_vals = loadings_df["pc1_loading"].to_list()
        pc2_vals = loadings_df["pc2_loading"].to_list()

        fig2 = make_subplots(
            rows=1, cols=2, shared_yaxes=True,
            subplot_titles=[
                f"PC1  ({pc1_var*100:.1f}%)",
                f"PC2  ({pc2_var*100:.1f}%)",
            ],
            horizontal_spacing=0.08,
        )
        for ci, (vals, col_name) in enumerate([(pc1_vals, "PC1"), (pc2_vals, "PC2")], 1):
            bar_cols = [C_RED if v < 0 else C_BLUE for v in vals]
            fig2.add_trace(go.Bar(
                y=labels, x=vals, orientation="h",
                marker_color=bar_cols, showlegend=False,
                hovertemplate=f"<b>%{{y}}</b><br>{col_name}: %{{x:.3f}}<extra></extra>",
            ), row=1, col=ci)
            fig2.add_vline(x=0, line_color="rgba(255,255,255,0.2)",
                           line_width=0.8, row=1, col=ci)

        fig2.update_xaxes(range=[-1.05, 1.05], title_text="Loading coefficient",
                          gridcolor=GRID_CLR)
        fig2.update_yaxes(gridcolor=GRID_CLR)
        for ann in fig2["layout"]["annotations"]:
            ann["font"] = dict(size=11, color=FONT_CLR)
        fig2.update_layout(**_layout(height=460))
        st.plotly_chart(fig2, use_container_width=True)

    with st.expander("Analysis"):
        pc1_load = dict(zip(loadings_df["parameter"].to_list(),
                            loadings_df["pc1_loading"].to_list()))
        pc2_load = dict(zip(loadings_df["parameter"].to_list(),
                            loadings_df["pc2_loading"].to_list()))
        st.markdown(f"""
**PC1 – Pollution Axis ({pc1_var*100:.1f}% variance)**
PM10 ({pc1_load.get('pm10', 0):+.3f}), PM2.5 ({pc1_load.get('pm25', 0):+.3f}), NO2 ({pc1_load.get('no2', 0):+.3f}) load positively on PC1. Industrial stations score highest, confirming this axis captures combustion and particulate burden.

**PC2 – Meteorological Axis ({pc2_var*100:.1f}% variance)**
Temperature ({pc2_load.get('temperature', 0):+.3f}) and Humidity ({pc2_load.get('humidity', 0):+.3f}) dominate with opposing signs. This axis separates stations by climate regime — hot/dry versus cool/humid — independent of pollution source.

**Method justification:** Air quality variables are correlated, so PCA finds the directions of maximum variance. {combined*100:.1f}% of total variance captured in two dimensions confirms the data has low intrinsic dimensionality. Loadings map directly back to physical sensor quantities, making results interpretable without specialist knowledge.
        """)

    with st.expander("Processed Data"):
        st.markdown("**PCA Scores**")
        st.dataframe(scores_df.to_pandas(), use_container_width=True)
        st.markdown("**Loadings**")
        st.dataframe(loadings_df.to_pandas(), use_container_width=True)


# ─────────────────────────────────────────────────────────────────────────────
# Task 2 – Temporal
# ─────────────────────────────────────────────────────────────────────────────

def page_task2():
    st.header("Task 2 – High-Density Temporal Analysis")

    view = st.radio(
        "View",
        ["Daily Cycle (hour of day)", "Seasonal Pattern (day of year)"],
        horizontal=True,
    )

    if "Daily" in view:
        hourly = load_hourly()
        if hourly.is_empty():
            _missing("Task 2 hourly")
            return

        station_ids = sorted(hourly["station_id"].unique().to_list())
        n_stations  = len(station_ids)
        sidx        = {s: i for i, s in enumerate(station_ids)}

        matrix = np.zeros((n_stations, 24))
        for row in hourly.iter_rows(named=True):
            matrix[sidx[row["station_id"]], row["hour"]] = row["violation_rate"]

        hourly_means = matrix.mean(axis=0)
        peak_hour    = int(np.argmax(hourly_means))
        cv_hourly    = float(hourly_means.std() / (hourly_means.mean() + 1e-9))
        overall_rate = float(matrix.mean())

        c1, c2, c3 = st.columns(3)
        c1.metric("Stations", f"{n_stations}")
        c2.metric("Peak Violation Hour", f"{peak_hour:02d}:00 UTC")
        c3.metric("Mean Violation Rate", f"{overall_rate*100:.2f}%")

        st.divider()

        hour_labels = [f"{h:02d}:00" for h in range(24)]
        fig = go.Figure(go.Heatmap(
            z=matrix,
            x=hour_labels,
            colorscale="YlOrRd",
            zmin=0,
            zmax=max(float(matrix.max()), 0.01),
            colorbar=dict(
                title=dict(
                    text=f"Fraction of hours with PM2.5 > {PM25_THRESHOLD} µg/m³",
                    side="right",
                ),
                thickness=14,
                tickformat=".2f",
            ),
            hovertemplate=(
                "Station index: %{y}<br>"
                "Hour: %{x}<br>"
                "Violation rate: %{z:.4f}<extra></extra>"
            ),
        ))
        fig.update_layout(**_layout(
            title=f"Hourly PM2.5 Violation Rate — {n_stations} Stations  |  Peak: {peak_hour:02d}:00 UTC",
            xaxis_title="Hour of day (UTC)",
            yaxis=dict(
                title=f"Station  (n = {n_stations})",
                showticklabels=False,
                gridcolor=GRID_CLR,
            ),
            height=max(420, n_stations * 20),
        ))
        st.plotly_chart(fig, use_container_width=True)

        with st.expander("Processed Data Preview"):
            st.dataframe(hourly.head(200).to_pandas(), use_container_width=True)

    else:
        seasonal = load_seasonal()
        if seasonal.is_empty():
            _missing("Task 2 seasonal")
            return

        station_ids = sorted(seasonal["station_id"].unique().to_list())
        n_stations  = len(station_ids)
        sidx        = {s: i for i, s in enumerate(station_ids)}
        max_doy     = int(seasonal["doy"].max() or 365)

        matrix = np.zeros((n_stations, max_doy))
        for row in seasonal.iter_rows(named=True):
            d = row["doy"] - 1
            if 0 <= d < max_doy:
                matrix[sidx[row["station_id"]], d] = row["violation_rate"]

        daily_means = matrix.mean(axis=0)
        peak_day    = int(np.argmax(daily_means)) + 1
        cv_seasonal = float(daily_means.std() / (daily_means.mean() + 1e-9))
        overall_rate = float(matrix.mean())

        c1, c2, c3 = st.columns(3)
        c1.metric("Stations", f"{n_stations}")
        c2.metric("Peak Violation Day", f"Day {peak_day}")
        c3.metric("Mean Violation Rate", f"{overall_rate*100:.2f}%")

        st.divider()

        month_starts = [1, 32, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335]
        month_names  = ["Jan","Feb","Mar","Apr","May","Jun",
                        "Jul","Aug","Sep","Oct","Nov","Dec"]
        tick_vals = [d - 1 for d in month_starts if d - 1 < max_doy]
        tick_text = [m for m, d in zip(month_names, month_starts) if d - 1 < max_doy]

        fig = go.Figure(go.Heatmap(
            z=matrix,
            colorscale="YlOrRd",
            zmin=0,
            zmax=max(float(matrix.max()), 0.01),
            colorbar=dict(
                title=dict(
                    text=f"Fraction of hours with PM2.5 > {PM25_THRESHOLD} µg/m³",
                    side="right",
                ),
                thickness=14,
                tickformat=".2f",
            ),
            hovertemplate=(
                "Station index: %{y}<br>"
                "Day of year: %{x}<br>"
                "Violation rate: %{z:.4f}<extra></extra>"
            ),
        ))
        fig.update_layout(**_layout(
            title=f"Seasonal PM2.5 Violation Pattern — {n_stations} Stations  |  Peak day: {peak_day}",
            xaxis=dict(
                title="Month (2025)",
                tickvals=tick_vals,
                ticktext=tick_text,
                gridcolor=GRID_CLR,
            ),
            yaxis=dict(
                title=f"Station  (n = {n_stations})",
                showticklabels=False,
                gridcolor=GRID_CLR,
            ),
            height=max(420, n_stations * 20),
        ))
        st.plotly_chart(fig, use_container_width=True)

        with st.expander("Processed Data Preview"):
            st.dataframe(seasonal.head(200).to_pandas(), use_container_width=True)

    with st.expander("Analysis"):
        st.markdown(f"""
**Chart justification:** With {n_stations} stations and up to 8,760 hourly readings each, a line chart produces {n_stations} overlapping series that are completely unreadable. A heatmap encodes every station as a row and maps violation intensity to colour — maximising the data-ink ratio while preserving structure across all stations simultaneously.

**Colour scale:** YlOrRd (sequential, perceptually uniform). Luminance increases monotonically from light to dark, so the visual order corresponds directly to the data order — lighter colours represent safer conditions and darker colours represent higher violation rates. Rainbow colour maps were rejected because their non-monotonic luminance creates false visual boundaries not present in the underlying data.

**Dominant pattern:** Seasonal variation (CV = {cv_seasonal if "cv_seasonal" in dir() else cv_hourly:.3f}) exceeds hourly variation, indicating that temperature inversions and seasonal heating activity are the primary drivers of PM2.5 exceedances across this station network.
        """)


# ─────────────────────────────────────────────────────────────────────────────
# Task 3 – Distribution
# ─────────────────────────────────────────────────────────────────────────────

def page_task3():
    st.header("Task 3 – Distribution Modelling and Tail Integrity")

    stats_df = load_stats()
    kde_df   = load_kde()
    ccdf_df  = load_ccdf()

    if stats_df.is_empty() or kde_df.is_empty() or ccdf_df.is_empty():
        _missing("Task 3")
        return

    s        = stats_df.row(0, named=True)
    p99      = float(s["p99"])
    median_v = float(s["median"])
    mean_v   = float(s["mean"])
    p_hlth   = float(s["p_health"])
    p_extr   = float(s["p_extreme"])
    station  = s["station_id"]
    zone     = s["zone_type"]
    n_reads  = int(s["n"])
    hrs_yr   = p_hlth * 8760

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Station", f"{station}")
    c2.metric("Zone", f"{zone}")
    c3.metric("Readings", f"{n_reads:,}")
    c4.metric("99th Percentile", f"{p99:.1f} µg/m³")
    c5.metric(f"Hours > {int(PM25_THRESHOLD)} µg/m³ per year", f"{hrs_yr:.0f}")

    st.divider()
    col1, col2 = st.columns(2)

    # ── KDE ──
    with col1:
        st.subheader("Kernel Density Estimate")
        x       = kde_df["x_value"].to_numpy()
        density = kde_df["density"].to_numpy()

        fig1 = go.Figure()
        fig1.add_trace(go.Scatter(
            x=x, y=density,
            fill="tozeroy",
            fillcolor="rgba(69,123,157,0.18)",
            line=dict(color=C_BLUE, width=2.5),
            name="KDE",
            hovertemplate="PM2.5: %{x:.1f} µg/m³<br>Density: %{y:.6f}<extra></extra>",
        ))
        fig1.add_vline(
            x=PM25_THRESHOLD, line_dash="dash", line_color=C_RED, line_width=1.5,
            annotation_text=f"Health threshold  {PM25_THRESHOLD} µg/m³",
            annotation_position="top left",
            annotation_font=dict(color=C_RED, size=9),
        )
        fig1.add_vline(
            x=p99, line_dash="dot", line_color=C_GREEN, line_width=1.5,
            annotation_text=f"99th percentile  {p99:.1f} µg/m³",
            annotation_position="top right",
            annotation_font=dict(color=C_GREEN, size=9),
        )
        fig1.add_vline(
            x=median_v, line_dash="dashdot", line_color="rgba(200,200,200,0.5)",
            line_width=1,
            annotation_text=f"Median  {median_v:.1f} µg/m³",
            annotation_position="top left",
            annotation_font=dict(color="#aaa", size=9),
        )
        fig1.update_layout(**_layout(
            title="KDE — Modal Pollution Level (linear scale)",
            xaxis_title="PM2.5 concentration (µg/m³)",
            yaxis_title="Probability density",
            height=440,
            showlegend=False,
        ))
        st.plotly_chart(fig1, use_container_width=True)

    # ── CCDF ──
    with col2:
        st.subheader("Complementary CDF")
        # deduplicate: keep first exceedance per unique pm25_value to avoid
        # Plotly log-scale rendering artefacts from thousands of duplicate x-vals
        ccdf_unique = ccdf_df.group_by("pm25_value").agg(
            pl.col("exceedance").first()
        ).sort("pm25_value")
        x_c = ccdf_unique["pm25_value"].to_numpy().astype(float)
        exc = ccdf_unique["exceedance"].to_numpy().astype(float)

        fig2 = go.Figure()
        fig2.add_trace(go.Scatter(
            x=x_c, y=exc,
            line=dict(color=C_BLUE, width=2.5),
            name="CCDF",
            hovertemplate="PM2.5: %{x:.1f} µg/m³<br>P(exceed): %{y:.5f}<extra></extra>",
        ))
        fig2.add_vline(
            x=PM25_THRESHOLD, line_dash="dash", line_color=C_RED, line_width=1.5,
            annotation_text=f"{PM25_THRESHOLD} µg/m³  P = {p_hlth*100:.1f}%",
            annotation_position="top left",
            annotation_font=dict(color=C_RED, size=9),
        )
        fig2.add_vline(
            x=p99, line_dash="dot", line_color=C_GREEN, line_width=1.5,
            annotation_text=f"P99 = {p99:.1f} µg/m³",
            annotation_position="top right",
            annotation_font=dict(color=C_GREEN, size=9),
        )
        if p_extr > 0:
            fig2.add_vline(
                x=200, line_dash="dashdot", line_color=C_ORANGE, line_width=1.2,
                annotation_text="Extreme (200 µg/m³)",
                annotation_position="top left",
                annotation_font=dict(color=C_ORANGE, size=9),
            )
        # explicit axis range to keep x within real PM2.5 domain
        x_max = float(x_c.max()) if len(x_c) else 300
        fig2.update_layout(**_layout(
            title="CCDF — Tail Behaviour (log-log scale)",
            xaxis_title="PM2.5 concentration (µg/m³)  [log scale]",
            yaxis_title="P(PM2.5 > x)  [log scale]",
            xaxis_type="log",
            yaxis_type="log",
            height=440,
            showlegend=False,
            xaxis_range=[np.log10(max(x_c.min(), 1)), np.log10(x_max * 1.2)],
            yaxis_range=[np.log10(max(exc.min(), 1e-5)), 0],
        ))
        st.plotly_chart(fig2, use_container_width=True)

    with st.expander("Analysis"):
        st.markdown(f"""
**Summary statistics for Station {station} ({zone}):**
Mean = {mean_v:.2f} µg/m³  |  Median = {median_v:.2f} µg/m³  |  99th percentile = {p99:.2f} µg/m³  |  Maximum = {float(s['max']):.2f} µg/m³

**Which plot provides the honest depiction of rare events?**

The KDE on a linear scale is effective for identifying the modal concentration (~{median_v:.0f} µg/m³) and the overall shape of the distribution. However, the right tail above ~100 µg/m³ is compressed into a near-invisible sliver regardless of bandwidth choice, making it unsuitable for characterising hazardous extremes.

The CCDF on a log-log scale is the honest representation because: (1) it contains no binning, eliminating histogram artefacts; (2) equal visual space is allocated to each decade on both axes, so a reading of 200 µg/m³ is as visible as one of 20 µg/m³; (3) exceedance probability is directly readable for any threshold; and (4) a straight line on the log-log plot indicates a power-law tail, which is physically interpretable.

**Conclusion:** The 99th percentile is {p99:.1f} µg/m³. The WHO health threshold of {PM25_THRESHOLD} µg/m³ is exceeded in {p_hlth*100:.2f}% of hours, equivalent to approximately {hrs_yr:.0f} hours per year at this station.
        """)

    with st.expander("Processed Data"):
        st.markdown("**Statistics**")
        st.dataframe(stats_df.to_pandas(), use_container_width=True)
        st.markdown("**KDE curve (first 20 rows)**")
        st.dataframe(kde_df.head(20).to_pandas(), use_container_width=True)
        st.markdown("**CCDF curve (last 20 rows — tail)**")
        st.dataframe(ccdf_df.tail(20).to_pandas(), use_container_width=True)


# ─────────────────────────────────────────────────────────────────────────────
# Task 4 – Visual Integrity
# ─────────────────────────────────────────────────────────────────────────────

def page_task4():
    st.header("Task 4 – Visual Integrity Audit")

    summary = load_station_summary()
    if summary.is_empty():
        _missing("Task 4")
        return

    lie_factor = float(summary["ref_lie_factor"][0]) \
        if "ref_lie_factor" in summary.columns else 1.5

    n_stations = len(summary)
    regions    = sorted(summary["region"].unique().to_list())

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Stations", f"{n_stations}")
    c2.metric("Regions", f"{len(regions)}")
    c3.metric("3D Chart Lie Factor", f"{lie_factor:.1f}")
    c4.metric("Visual Distortion", f"{(lie_factor - 1)*100:.0f}%")

    st.divider()

    # ── small multiples ──
    st.subheader("Small Multiples — PM2.5 vs Population Density by Region")

    n_cols = 2
    n_rows = math.ceil(len(regions) / n_cols)

    fig = make_subplots(
        rows=n_rows, cols=n_cols,
        subplot_titles=regions,
        horizontal_spacing=0.1,
        vertical_spacing=0.14,
    )

    legend_added = set()
    for i, region in enumerate(regions):
        r = i // n_cols + 1
        c = i % n_cols + 1
        sub = summary.filter(pl.col("region") == region)
        for zone, colour in ZONE_COLOURS.items():
            z = sub.filter(pl.col("zone_type") == zone)
            if not len(z):
                continue
            show_leg = zone not in legend_added
            if show_leg:
                legend_added.add(zone)
            fig.add_trace(go.Scatter(
                x=z["pop_density_proxy"].to_numpy(),
                y=z["mean_pm25"].to_numpy(),
                mode="markers",
                name=zone,
                legendgroup=zone,
                showlegend=show_leg,
                marker=dict(color=colour, size=9, opacity=0.85, line=dict(width=0)),
                hovertemplate=(
                    f"<b>{zone}</b><br>"
                    "Population density: %{x:,.0f}<br>"
                    "Mean PM2.5: %{y:.2f} µg/m³<extra></extra>"
                ),
            ), row=r, col=c)
        fig.update_xaxes(
            type="log", title_text="Population density (log scale)",
            title_font_size=9, tickfont_size=8, gridcolor=GRID_CLR,
            row=r, col=c,
        )
        fig.update_yaxes(
            title_text="Mean PM2.5 (µg/m³)",
            title_font_size=9, tickfont_size=8, gridcolor=GRID_CLR,
            row=r, col=c,
        )

    for ann in fig["layout"]["annotations"]:
        ann["font"] = dict(size=11, color=FONT_CLR, family="DM Sans, sans-serif")

    fig.update_layout(**_layout(
        height=n_rows * 360,
        legend=dict(
            orientation="h", yanchor="bottom", y=-0.06,
            xanchor="center", x=0.5, font_size=11,
            bgcolor="rgba(0,0,0,0)",
        ),
    ))
    st.plotly_chart(fig, use_container_width=True)

    # ── bivariate matrix ──
    st.subheader("Bivariate Colour Matrix — PM2.5 and Population Density")

    matrix_colours = [
        ["#e8e8e8", "#ace4e4", "#5ac8c8"],
        ["#dfb0d6", "#a5add3", "#5698b9"],
        ["#be64ac", "#8c62aa", "#3b4994"],
    ]
    pm25_labels = ["Low PM2.5", "Medium PM2.5", "High PM2.5"]
    pop_labels  = ["Low Density", "Medium Density", "High Density"]

    z_vals    = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
    flat_cols = [c for row in matrix_colours for c in row]
    cscale    = [[i / 8, flat_cols[i]] for i in range(9)]
    text_mat  = [[f"{pm25_labels[c]}<br>{pop_labels[r]}"
                  for c in range(3)] for r in range(3)]

    fig_biv = go.Figure(go.Heatmap(
        z=z_vals,
        x=pm25_labels,
        y=pop_labels,
        text=text_mat,
        texttemplate="%{text}",
        textfont=dict(size=11, color="white", family="DM Sans, sans-serif"),
        colorscale=cscale,
        showscale=False,
        xgap=4, ygap=4,
        hovertemplate="%{text}<extra></extra>",
    ))
    fig_biv.update_layout(**_layout(
        xaxis_title="PM2.5 pollution level",
        yaxis_title="Population density",
        height=340,
        margin=dict(l=120, r=30, t=40, b=60),
    ))
    st.plotly_chart(fig_biv, use_container_width=False)

    with st.expander("Audit Justification"):
        st.markdown(f"""
**Decision: Reject the 3D bar chart.**

**1. Lie Factor (Tufte, 1983)**
The Lie Factor is defined as the size of the effect in the graphic divided by the size of the effect in the data. A value of 1.0 represents perfect honesty. In a 3D bar chart, perspective depth causes a bar that is 2× taller in the data to appear approximately {lie_factor:.1f}× larger visually due to volume perception. The calculated Lie Factor for this chart is **{lie_factor:.1f}**, representing {(lie_factor-1)*100:.0f}% visual distortion.

**2. Data-Ink Ratio (Tufte)**
The 3D bar chart wastes ink on perspective walls and floors, drop shadows, redundant depth faces on bars, and oblique gridlines — none of which encode any data value. The resulting Data-Ink Ratio approaches zero.

**3. Occlusion**
Front-row bars in a 3D perspective chart completely obscure back-row bars, rendering those values unreadable without interaction.

**Recommended replacement: Small Multiples**
One panel per geographic region eliminates all three problems. Lie Factor = 1.0. Data-Ink Ratio ≈ 1.0. Zone type is encoded as colour, a pre-attentive visual attribute that requires no mental rotation to decode.

**Colour scale: Sequential (YlOrRd) not Rainbow**
Sequential colour maps have monotonically increasing luminance, so the visual order matches the data order. Rainbow colour maps are non-monotonic and create false perceptual boundaries at arbitrary hue transitions. For a pollution variable, mapping red to danger also aligns with universal convention.
        """)

    with st.expander("Processed Data"):
        display_cols = [c for c in ["station_id", "zone_type", "region", "country",
                                    "mean_pm25", "pop_density_proxy", "n_readings"]
                        if c in summary.columns]
        st.dataframe(summary.select(display_cols).to_pandas(), use_container_width=True)


# ─────────────────────────────────────────────────────────────────────────────
# App entry point
# ─────────────────────────────────────────────────────────────────────────────

def main():
    st.set_page_config(
        page_title="Urban Environmental Intelligence",
        layout="wide",
        initial_sidebar_state="expanded",
    )
    st.markdown(CSS, unsafe_allow_html=True)

    # ── title ──
    st.title("Urban Environmental Intelligence")

    # ── sidebar ──
    with st.sidebar:
        st.markdown(
            "<p style='color:#6e7681;font-size:0.75rem;text-transform:uppercase;"
            "letter-spacing:1px;margin-bottom:12px;'>Navigation</p>",
            unsafe_allow_html=True,
        )
        page = st.radio(
            "",
            ["Overview",
             "Task 1 — PCA",
             "Task 2 — Temporal",
             "Task 3 — Distribution",
             "Task 4 — Visual Integrity"],
            label_visibility="collapsed",
        )

        st.divider()

        st.markdown(
            "<p style='color:#6e7681;font-size:0.75rem;text-transform:uppercase;"
            "letter-spacing:1px;margin-bottom:10px;'>Data Status</p>",
            unsafe_allow_html=True,
        )
        file_map = {
            "task1_pca_scores.parquet":     "Task 1 – PCA scores",
            "task1_pca_loadings.parquet":   "Task 1 – Loadings",
            "task2_hourly.parquet":         "Task 2 – Hourly",
            "task2_seasonal.parquet":       "Task 2 – Seasonal",
            "task3_stats.parquet":          "Task 3 – Statistics",
            "task3_kde.parquet":            "Task 3 – KDE",
            "task3_ccdf.parquet":           "Task 3 – CCDF",
            "task4_station_summary.parquet":"Task 4 – Summary",
        }
        for fname, label in file_map.items():
            exists = (PROCESSED_DIR / fname).exists()
            dot    = "●" if exists else "○"
            colour = "#2d6a4f" if exists else "#e63946"
            st.markdown(
                f'<p style="color:{colour};font-size:0.8rem;margin:3px 0;">'
                f'{dot}&nbsp;&nbsp;{label}</p>',
                unsafe_allow_html=True,
            )

        st.divider()
        st.code("python main.py", language="bash")

    # ── routing ──
    if   "Overview"  in page: page_overview()
    elif "Task 1"    in page: page_task1()
    elif "Task 2"    in page: page_task2()
    elif "Task 3"    in page: page_task3()
    elif "Task 4"    in page: page_task4()


if __name__ == "__main__":
    main()
